sudo: required
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule ansible docker yamllint

script:
  - find . -name "*.yml" | xargs yamllint
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
