---

- name: 'Verify the version of your OS'
  fail:
    msg: 'Operating system unsupported'
  when: ansible_os_family != "RedHat"
  tags:
    - postgres

- name: 'Ensure base_postgres_user and base_postgres_pass are defined.'
  fail:
    msg: 'variables undefined'
  when:
    - base_postgres_user is undefined
    - base_postgres_pass is undefined
  tags:
    - postgres

- name: Install as root
  include_tasks: install.yml

- name: Configure as postgres
  include_tasks: config.yml
...
