---
- name: Change group postgres'
  file:
    path: "{{ item }}"
    group: postgres
    mode: 0640
  with_items:
    - "{{ postgresql_ssl_ca_file }}"
    - "{{ postgresql_ssl_cert_file }}"
    - "{{ postgresql_ssl_key_file }}"
    - /etc/ssl/postgresql/

- name: Enable ssl
  become: true
  lineinfile:
    dest: /var/lib/pgsql/{{ base_postgres_m }}/data/postgresql.conf
    insertafter: '^#ssl = off'
    line: "ssl = on"
    state: present

- name: Enable ssl_ca_fil
  become: true
  lineinfile:
    dest: /var/lib/pgsql/{{ base_postgres_m }}/data/postgresql.conf
    insertafter: '^#ssl_ca_file'
    line: "ssl_ca_file = '{{ postgresql_ssl_ca_file }}'"
    state: present

- name: Enable ssl_cert_file
  become: true
  lineinfile:
    dest: /var/lib/pgsql/{{ base_postgres_m }}/data/postgresql.conf
    insertafter: '^#ssl_cert_file'
    line: "ssl_cert_file = '{{ postgresql_ssl_cert_file }}'"
    state: present

- name: Enable ssl_key_file
  become: true
  lineinfile:
    dest: /var/lib/pgsql/{{ base_postgres_m }}/data/postgresql.conf
    insertafter: '^#ssl_key_file'
    line: "ssl_key_file = '{{ postgresql_ssl_key_file }}'"
    state: present
...
