---

driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later -qq
platforms:
  - name: primary-postgres-centos8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    privileged: true
    groups:
      - postgres
    docker_networks:
      - name: 'postgres'
        ipam_config:
          - subnet: '10.16.1.0/24'
    networks:
      - name: "postgres"
        ipv4_address: '10.16.1.12'
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: replica-postgres-centos8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    privileged: true
    groups:
      - postgres
    docker_networks:
      - name: 'postgres'
        ipam_config:
          - subnet: '10.16.1.0/24'
    networks:
      - name: "postgres"
        ipv4_address: '10.16.1.13'
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      executable: /bin/bash
  inventory:
    host_vars:
      primary-postgres-centos8:
        base_postgres_role: primary
      replica-postgres-centos8:
        base_postgres_role: replica
  playbooks:
    dependency: ../resources/dependency.yml
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml
verifier:
  name: ansible
