---

# handlers file for actions that are notified: by a play
- name: 'start postgresql'
  become: yes
  service:
    name: "postgresql-{{ base_postgres_m }}"
    state: started

- name: 'restart postgresql'
  become: yes
  service:
    name: "postgresql-{{ base_postgres_m }}"
    state: restarted

#- name: 'restart iptables'
#  become: yes
#  service: name=iptables state=restarted
