---

# handlers file for actions that are notified: by a play
- name: Start postgresql
  become: true
  systemd:
    name: "{{ base_postgres_service }}"
    state: started

- name: Restart postgresql
  become: true
  systemd:
    name: "{{ base_postgres_service }}"
    state: restarted

...
