---

# handlers file for actions that are notified: by a play
- name: Start postgresql
  become: true
  systemd:
    name: "postgresql-{{ base_postgres_m }}"
    state: started

- name: Restart postgresql
  become: true
  systemd:
    name: "postgresql-{{ base_postgres_m }}"
    state: restarted

...
