---

dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later -qq
platforms:
  - name: base-postgres-centos8
    image: quay.io/centos/centos:stream8
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: base-postgres-centos7
    image: centos/systemd
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
