---

dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker
lint:
  name: yamllint

platforms:
  - name: base-postgres-centos7
    image: milcom/centos7-systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      stdout_callback: yaml
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: yamllint
