---

dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-postgres-centos7
    image: milcom/centos7-systemd
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
