---

dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker
lint:
  name: yamllint

platforms:
  - name: base-postgres-centos7
    image: milcom/centos7-systemd
    privileged: true
  - name: base-postgres-centos6
    image: centos:6
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: yamllint
