---

dependency:
  name: galaxy
  requirements_file: requirements.yml

driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  ansible-later -qq
platforms:
  - name: primary-postgres-centos7
    image: centos/systemd
    command: /sbin/init
    privileged: true
    groups:
      - postgres_master
    docker_networks:
      - name: 'postgres'
        ipam_config:
          - subnet: '10.16.1.0/24'
    networks:
      - name: "postgres"
        ipv4_address: '10.16.1.10'
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: replica-postgres-centos7
    image: centos/systemd
    command: /sbin/init
    privileged: true
    groups:
      - postgres_replica
    docker_networks:
      - name: 'postgres'
        ipam_config:
          - subnet: '10.16.1.0/24'
    networks:
      - name: "postgres"
        ipv4_address: '10.16.1.11'
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      executable: /bin/bash
  inventory:
    group_vars:
      all:
        base_postgres_mip: '10.16.1.10'
        base_postgres_sip: '10.16.1.11'
    host_vars:
      primary-postgres-centos8:
        base_postgres_role: primary
      replica-postgres-centos8:
        base_postgres_role: replica
  playbooks:
    dependency: ../resources/dependency.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    verify: ../resources/verify.yml
verifier:
  name: ansible
